---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-machine-learning/resources/bANLa) course resource._

---

## Assignment 4 - Understanding and Predicting Property Maintenance Fines

This assignment is based on a data challenge from the Michigan Data Science Team ([MDST](http://midas.umich.edu/mdst/)). 

The Michigan Data Science Team ([MDST](http://midas.umich.edu/mdst/)) and the Michigan Student Symposium for Interdisciplinary Statistical Sciences ([MSSISS](https://sites.lsa.umich.edu/mssiss/)) have partnered with the City of Detroit to help solve one of the most pressing problems facing Detroit - blight. [Blight violations](http://www.detroitmi.gov/How-Do-I/Report/Blight-Complaint-FAQs) are issued by the city to individuals who allow their properties to remain in a deteriorated condition. Every year, the city of Detroit issues millions of dollars in fines to residents and every year, many of these fines remain unpaid. Enforcing unpaid blight fines is a costly and tedious process, so the city wants to know: how can we increase blight ticket compliance?

The first step in answering this question is understanding when and why a resident might fail to comply with a blight ticket. This is where predictive modeling comes in. For this assignment, your task is to predict whether a given blight ticket will be paid on time.

All data for this assignment has been provided to us through the [Detroit Open Data Portal](https://data.detroitmi.gov/). **Only the data already included in your Coursera directory can be used for training the model for this assignment.** Nonetheless, we encourage you to look into data from other Detroit datasets to help inform feature creation and model selection. We recommend taking a look at the following related datasets:

* [Building Permits](https://data.detroitmi.gov/Property-Parcels/Building-Permits/xw2a-a7tf)
* [Trades Permits](https://data.detroitmi.gov/Property-Parcels/Trades-Permits/635b-dsgv)
* [Improve Detroit: Submitted Issues](https://data.detroitmi.gov/Government/Improve-Detroit-Submitted-Issues/fwz3-w3yn)
* [DPD: Citizen Complaints](https://data.detroitmi.gov/Public-Safety/DPD-Citizen-Complaints-2016/kahe-efs3)
* [Parcel Map](https://data.detroitmi.gov/Property-Parcels/Parcel-Map/fxkw-udwf)

___

We provide you with two data files for use in training and validating your models: train.csv and test.csv. Each row in these two files corresponds to a single blight ticket, and includes information about when, why, and to whom each ticket was issued. The target variable is compliance, which is True if the ticket was paid early, on time, or within one month of the hearing data, False if the ticket was paid after the hearing date or not at all, and Null if the violator was found not responsible. Compliance, as well as a handful of other variables that will not be available at test-time, are only included in train.csv.

Note: All tickets where the violators were found not responsible are not considered during evaluation. They are included in the training set as an additional source of data for visualization, and to enable unsupervised and semi-supervised approaches. However, they are not included in the test set.

<br>

**File descriptions** (Use only this data for training your model!)

    readonly/train.csv - the training set (all tickets issued 2004-2011)
    readonly/test.csv - the test set (all tickets issued 2012-2016)
    readonly/addresses.csv & readonly/latlons.csv - mapping from ticket id to addresses, and from addresses to lat/lon coordinates. 
     Note: misspelled addresses may be incorrectly geolocated.

<br>

**Data fields**

train.csv & test.csv

    ticket_id - unique identifier for tickets
    agency_name - Agency that issued the ticket
    inspector_name - Name of inspector that issued the ticket
    violator_name - Name of the person/organization that the ticket was issued to
    violation_street_number, violation_street_name, violation_zip_code - Address where the violation occurred
    mailing_address_str_number, mailing_address_str_name, city, state, zip_code, non_us_str_code, country - Mailing address of the violator
    ticket_issued_date - Date and time the ticket was issued
    hearing_date - Date and time the violator's hearing was scheduled
    violation_code, violation_description - Type of violation
    disposition - Judgment and judgement type
    fine_amount - Violation fine amount, excluding fees
    admin_fee - $20 fee assigned to responsible judgments
state_fee - $10 fee assigned to responsible judgments
    late_fee - 10% fee assigned to responsible judgments
    discount_amount - discount applied, if any
    clean_up_cost - DPW clean-up or graffiti removal cost
    judgment_amount - Sum of all fines and fees
    grafitti_status - Flag for graffiti violations
    
train.csv only

    payment_amount - Amount paid, if any
    payment_date - Date payment was made, if it was received
    payment_status - Current payment status as of Feb 1 2017
    balance_due - Fines and fees still owed
    collection_status - Flag for payments in collections
    compliance [target variable for prediction] 
     Null = Not responsible
     0 = Responsible, non-compliant
     1 = Responsible, compliant
    compliance_detail - More information on why each ticket was marked compliant or non-compliant


___

## Evaluation

Your predictions will be given as the probability that the corresponding blight ticket will be paid on time.

The evaluation metric for this assignment is the Area Under the ROC Curve (AUC). 

Your grade will be based on the AUC score computed for your classifier. A model which with an AUROC of 0.7 passes this assignment, over 0.75 will recieve full points.
___

For this assignment, create a function that trains a model to predict blight ticket compliance in Detroit using `readonly/train.csv`. Using this model, return a series of length 61001 with the data being the probability that each corresponding ticket from `readonly/test.csv` will be paid, and the index being the ticket_id.

Example:

    ticket_id
       284932    0.531842
       285362    0.401958
       285361    0.105928
       285338    0.018572
                 ...
       376499    0.208567
       376500    0.818759
       369851    0.018528
       Name: compliance, dtype: float32
       
### Hints

* Make sure your code is working before submitting it to the autograder.

* Print out your result to see whether there is anything weird (e.g., all probabilities are the same).

* Generally the total runtime should be less than 10 mins. You should NOT use Neural Network related classifiers (e.g., MLPClassifier) in this question. 

* Try to avoid global variables. If you have other functions besides blight_model, you should move those functions inside the scope of blight_model.

* Refer to the pinned threads in Week 4's discussion forum when there is something you could not figure it out.

In [5]:
import pandas as pd
import numpy as np

In [6]:
#blight_model()

In [7]:
#import data
train_data = pd.read_csv('train.csv', engine='python')
test_data = pd.read_csv('test.csv', engine='python')

In [8]:
#check data 
train_data.head()

,ticket_id,agency_name,inspector_name,violator_name,violation_street_number,violation_street_name,violation_zip_code,mailing_address_str_number,mailing_address_str_name,city,...,clean_up_cost,judgment_amount,payment_amount,balance_due,payment_date,payment_status,collection_status,grafitti_status,compliance_detail,compliance
0,22056,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","INVESTMENT INC., MIDWEST MORTGAGE",2900.0,TYLER,NaN,3.0,S. WICKER,CHICAGO,...,0.0,305.0,0.0,305.0,NaN,NO PAYMENT APPLIED,NaN,NaN,non-compliant by no payment,0.0
1,27586,"Buildings, Safety Engineering & Env Department","Williams, Darrin","Michigan, Covenant House",4311.0,CENTRAL,NaN,2959.0,Martin Luther King,Detroit,...,0.0,855.0,780.0,75.0,2005-06-02 00:00:00,PAID IN FULL,NaN,NaN,compliant by late payment within 1 month,1.0
2,22062,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","SANDERS, DERRON",1449.0,LONGFELLOW,NaN,23658.0,P.O. BOX,DETROIT,...,0.0,0.0,0.0,0.0,NaN,NO PAYMENT APPLIED,NaN,NaN,not responsible by disposition,NaN
3,22084,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","MOROSI, MIKE",1441.0,LONGFELLOW,NaN,5.0,ST. CLAIR,DETROIT,...,0.0,0.0,0.0,0.0,NaN,NO PAYMENT APPLIED,NaN,NaN,not responsible by disposition,NaN
4,22093,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","NATHANIEL, NEAL",2449.0,CHURCHILL,NaN,7449.0,CHURCHILL,DETROIT,...,0.0,0.0,0.0,0.0,NaN,NO PAYMENT APPLIED,NaN,NaN,not responsible by disposition,NaN

In [9]:
test_data.head()

,ticket_id,agency_name,inspector_name,violator_name,violation_street_number,violation_street_name,violation_zip_code,mailing_address_str_number,mailing_address_str_name,city,...,violation_description,disposition,fine_amount,admin_fee,state_fee,late_fee,discount_amount,clean_up_cost,judgment_amount,grafitti_status
0,284932,Department of Public Works,"Granberry, Aisha B","FLUELLEN, JOHN A",10041.0,ROSEBERRY,NaN,141,ROSEBERRY,DETROIT,...,Failure to secure City or Private solid waste ...,Responsible by Default,200.0,20.0,10.0,20.0,0.0,0.0,250.0,NaN
1,285362,Department of Public Works,"Lusk, Gertrina","WHIGHAM, THELMA",18520.0,EVERGREEN,NaN,19136,GLASTONBURY,DETROIT,...,Allowing bulk solid waste to lie or accumulate...,Responsible by Default,1000.0,20.0,10.0,100.0,0.0,0.0,1130.0,NaN
2,285361,Department of Public Works,"Lusk, Gertrina","WHIGHAM, THELMA",18520.0,EVERGREEN,NaN,19136,GLASTONBURY,DETROIT,...,Improper placement of Courville container betw...,Responsible by Default,100.0,20.0,10.0,10.0,0.0,0.0,140.0,NaN
3,285338,Department of Public Works,"Talbert, Reginald","HARABEDIEN, POPKIN",1835.0,CENTRAL,NaN,2246,NELSON,WOODHAVEN,...,Allowing bulk solid waste to lie or accumulate...,Responsible by Default,200.0,20.0,10.0,20.0,0.0,0.0,250.0,NaN
4,285346,Department of Public Works,"Talbert, Reginald","CORBELL, STANLEY",1700.0,CENTRAL,NaN,3435,MUNGER,LIVONIA,...,Violation of time limit for approved container...,Responsible by Default,100.0,20.0,10.0,10.0,0.0,0.0,140.0,NaN

In [10]:
print("train data column list: {}\n".format(train_data.columns))
print("test data column list: {}\n".format(test_data.columns))

train data column list: Index(['ticket_id', 'agency_name', 'inspector_name', 'violator_name',
       'violation_street_number', 'violation_street_name',
       'violation_zip_code', 'mailing_address_str_number',
       'mailing_address_str_name', 'city', 'state', 'zip_code',
       'non_us_str_code', 'country', 'ticket_issued_date', 'hearing_date',
       'violation_code', 'violation_description', 'disposition', 'fine_amount',
       'admin_fee', 'state_fee', 'late_fee', 'discount_amount',
       'clean_up_cost', 'judgment_amount', 'payment_amount', 'balance_due',
       'payment_date', 'payment_status', 'collection_status',
       'grafitti_status', 'compliance_detail', 'compliance'],
      dtype='object')

test data column list: Index(['ticket_id', 'agency_name', 'inspector_name', 'violator_name',
       'violation_street_number', 'violation_street_name',
       'violation_zip_code', 'mailing_address_str_number',
       'mailing_address_str_name', 'city', 'state', 'zip_code',
       'non_us_str_code', 'country', 'ticket_issued_date', 'hearing_date',
       'violation_code', 'violation_description', 'disposition', 'fine_amount',
       'admin_fee', 'state_fee', 'late_fee', 'discount_amount',
       'clean_up_cost', 'judgment_amount', 'grafitti_status'],
      dtype='object')

We observe that the data is imbalanced towards the non-compliant class, since the number of observations belonging to compliant class is significantly lower than the number of observations for the non-compliant class. Necessary steps will have to be taken to ensure that the model doesn't always return 0

In [11]:
train_data["compliance"].value_counts()

0.0    148283
1.0     11597
Name: compliance, dtype: int64

In [12]:
print("Ratio of compliant to non-compliant classes: {:.2f}".format(11597/148283))

Ratio of compliant to non-compliant classes: 0.08

Let's start by removing rows in which violaters were found not guilty of the violation. We do not plan to model semi-supervised and unsupervised learning algorithms as mentioned in the problem statement

In [13]:
train_data = train_data[train_data["compliance"].notna()]
train_data.head()

,ticket_id,agency_name,inspector_name,violator_name,violation_street_number,violation_street_name,violation_zip_code,mailing_address_str_number,mailing_address_str_name,city,...,clean_up_cost,judgment_amount,payment_amount,balance_due,payment_date,payment_status,collection_status,grafitti_status,compliance_detail,compliance
0,22056,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","INVESTMENT INC., MIDWEST MORTGAGE",2900.0,TYLER,NaN,3.0,S. WICKER,CHICAGO,...,0.0,305.0,0.0,305.0,NaN,NO PAYMENT APPLIED,NaN,NaN,non-compliant by no payment,0.0
1,27586,"Buildings, Safety Engineering & Env Department","Williams, Darrin","Michigan, Covenant House",4311.0,CENTRAL,NaN,2959.0,Martin Luther King,Detroit,...,0.0,855.0,780.0,75.0,2005-06-02 00:00:00,PAID IN FULL,NaN,NaN,compliant by late payment within 1 month,1.0
5,22046,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","KASIMU, UKWELI",6478.0,NORTHFIELD,NaN,2755.0,E. 17TH,LOG BEACH,...,0.0,305.0,0.0,305.0,NaN,NO PAYMENT APPLIED,NaN,NaN,non-compliant by no payment,0.0
6,18738,"Buildings, Safety Engineering & Env Department","Williams, Darrin","Deerwood Development Group Inc, Deer",8027.0,BRENTWOOD,NaN,476.0,Garfield,Clinton,...,0.0,855.0,0.0,855.0,NaN,NO PAYMENT APPLIED,NaN,NaN,non-compliant by no payment,0.0
7,18735,"Buildings, Safety Engineering & Env Department","Williams, Darrin","Rafee Auto Services L.L.C., RAF",8228.0,MT ELLIOTT,NaN,8228.0,Mt. Elliott,Detroit,...,0.0,140.0,0.0,140.0,NaN,NO PAYMENT APPLIED,NaN,NaN,non-compliant by no payment,0.0

We must remove columns which might leak target data to the model, luckily we can use the list of columns given in test.csv as independent variables and the target variable compliance as the dependent variable. Since other variables in train.csv were not deemed fit by the problem setter, they must be leaking data to the model.

In [14]:
train_data = train_data[['ticket_id', 'agency_name', 'inspector_name', 'violator_name',
       'violation_street_number', 'violation_street_name',
       'violation_zip_code', 'mailing_address_str_number',
       'mailing_address_str_name', 'city', 'state', 'zip_code',
       'non_us_str_code', 'country', 'ticket_issued_date', 'hearing_date',
       'violation_code', 'violation_description', 'disposition', 'fine_amount',
       'admin_fee', 'state_fee', 'late_fee', 'discount_amount',
       'clean_up_cost', 'judgment_amount', 'grafitti_status', 'compliance']]
train_data.head()

,ticket_id,agency_name,inspector_name,violator_name,violation_street_number,violation_street_name,violation_zip_code,mailing_address_str_number,mailing_address_str_name,city,...,disposition,fine_amount,admin_fee,state_fee,late_fee,discount_amount,clean_up_cost,judgment_amount,grafitti_status,compliance
0,22056,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","INVESTMENT INC., MIDWEST MORTGAGE",2900.0,TYLER,NaN,3.0,S. WICKER,CHICAGO,...,Responsible by Default,250.0,20.0,10.0,25.0,0.0,0.0,305.0,NaN,0.0
1,27586,"Buildings, Safety Engineering & Env Department","Williams, Darrin","Michigan, Covenant House",4311.0,CENTRAL,NaN,2959.0,Martin Luther King,Detroit,...,Responsible by Determination,750.0,20.0,10.0,75.0,0.0,0.0,855.0,NaN,1.0
5,22046,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","KASIMU, UKWELI",6478.0,NORTHFIELD,NaN,2755.0,E. 17TH,LOG BEACH,...,Responsible by Default,250.0,20.0,10.0,25.0,0.0,0.0,305.0,NaN,0.0
6,18738,"Buildings, Safety Engineering & Env Department","Williams, Darrin","Deerwood Development Group Inc, Deer",8027.0,BRENTWOOD,NaN,476.0,Garfield,Clinton,...,Responsible by Default,750.0,20.0,10.0,75.0,0.0,0.0,855.0,NaN,0.0
7,18735,"Buildings, Safety Engineering & Env Department","Williams, Darrin","Rafee Auto Services L.L.C., RAF",8228.0,MT ELLIOTT,NaN,8228.0,Mt. Elliott,Detroit,...,Responsible by Default,100.0,20.0,10.0,10.0,0.0,0.0,140.0,NaN,0.0

We observe that some features of the training dataframe have categorical values, these values should be encoded to numnerical values using OneHotEncoder. Nan and Null values must also be changed to either the mean or the median of the feature depending on the skewness of data.

In [15]:
print("Total number of rows/observations : {}".format(len(train_data.index)) )
print("NaN value counts: ")
train_data.drop(['violation_zip_code','non_us_str_code','grafitti_status'],axis = 1, inplace = True)
test_data.drop(['violation_zip_code','non_us_str_code','grafitti_status'],axis = 1, inplace = True)
train_data.dropna(inplace = True)
train_data.dropna(inplace = True)
train_data.isnull().sum()

Total number of rows/observations : 159880
NaN value counts:

ticket_id                     0
agency_name                   0
inspector_name                0
violator_name                 0
violation_street_number       0
violation_street_name         0
mailing_address_str_number    0
mailing_address_str_name      0
city                          0
state                         0
zip_code                      0
country                       0
ticket_issued_date            0
hearing_date                  0
violation_code                0
violation_description         0
disposition                   0
fine_amount                   0
admin_fee                     0
state_fee                     0
late_fee                      0
discount_amount               0
clean_up_cost                 0
judgment_amount               0
compliance                    0
dtype: int64

In [16]:
print("Total number of rows/observations after removing null data : {}".format(len(train_data.index)) )
print("Total number of rows/observations in test set after removing null data : {}".format(len(test_data.index)) )

Total number of rows/observations after removing null data : 156999
Total number of rows/observations in test set after removing null data : 61001

In [17]:
#train_data.isna().sum()

In [18]:
train_data.dtypes

ticket_id                       int64
agency_name                    object
inspector_name                 object
violator_name                  object
violation_street_number       float64
violation_street_name          object
mailing_address_str_number    float64
mailing_address_str_name       object
city                           object
state                          object
zip_code                       object
country                        object
ticket_issued_date             object
hearing_date                   object
violation_code                 object
violation_description          object
disposition                    object
fine_amount                   float64
admin_fee                     float64
state_fee                     float64
late_fee                      float64
discount_amount               float64
clean_up_cost                 float64
judgment_amount               float64
compliance                    float64
dtype: object

In [19]:
print('Columns with non-numeric data: \n')
data_types = train_data.dtypes
data_types[data_types == np.dtype('O')]

Columns with non-numeric data:

agency_name                 object
inspector_name              object
violator_name               object
violation_street_name       object
mailing_address_str_name    object
city                        object
state                       object
zip_code                    object
country                     object
ticket_issued_date          object
hearing_date                object
violation_code              object
violation_description       object
disposition                 object
dtype: object

In [20]:
non_numeric_columns = data_types[data_types == np.dtype('O')].index.tolist()
print('non-numeric columns: ')
print(*non_numeric_columns, sep = '\n')

non-numeric columns:
agency_name
inspector_name
violator_name
violation_street_name
mailing_address_str_name
city
state
zip_code
country
ticket_issued_date
hearing_date
violation_code
violation_description
disposition

In [21]:
for feature_name in non_numeric_columns:
    print("Number of unique values for the feature {}: {}".format(feature_name, len(train_data[feature_name].unique())))

Number of unique values for the feature agency_name: 5
Number of unique values for the feature inspector_name: 159
Number of unique values for the feature violator_name: 83406
Number of unique values for the feature violation_street_name: 1711
Number of unique values for the feature mailing_address_str_name: 26831
Number of unique values for the feature city: 3942
Number of unique values for the feature state: 57
Number of unique values for the feature zip_code: 3370
Number of unique values for the feature country: 3
Number of unique values for the feature ticket_issued_date: 67253
Number of unique values for the feature hearing_date: 5958
Number of unique values for the feature violation_code: 188
Number of unique values for the feature violation_description: 206
Number of unique values for the feature disposition: 4

Agency_name, country and disposition are featues which stand out as candidates for One-Hot Encoding. We may also encode other non-numeric features with <200 unique counts  - State, violation_code and inspector_name. Since One-Hot Encoding adds x columns for x unique values per feature, we cannot encode every non-numeric column. We need to carefully consider if these non-numeric features should be dropped or encoded as most algorithms tend to fare worse on sparse data.

In [22]:
train_data.drop([
 'inspector_name',
 'violation_street_name',
 'mailing_address_str_name',
 'city',
 'state',
 'zip_code',
 'country',
 'ticket_issued_date',
 'hearing_date',
 'violation_description',
  "mailing_address_str_number", "violation_street_number", 'violator_name'],axis = 1, inplace = True)
test_data.drop([
 'inspector_name',
 'violation_street_name',
 'mailing_address_str_name',
 'city',
 'state',
 'zip_code',
 'country',
 'ticket_issued_date',
 'hearing_date',
 'violation_description',
  "mailing_address_str_number", "violation_street_number", 'violator_name'],axis = 1, inplace = True)
train_data.isna().sum()

ticket_id          0
agency_name        0
violation_code     0
disposition        0
fine_amount        0
admin_fee          0
state_fee          0
late_fee           0
discount_amount    0
clean_up_cost      0
judgment_amount    0
compliance         0
dtype: int64

Extracting the first two digits from 'violation code' should reduce the number of unique elements in the feature

In [23]:
import re
train_data['violation_code_extracted'] = train_data['violation_code'].str.extract(r"^([0-9]+(-[0-9]+)?).*")[0]
test_data['violation_code_extracted'] = test_data['violation_code'].str.extract(r"^([0-9]+(-[0-9]+)?).*")[0]

np.sort(train_data['violation_code_extracted'].unique())
train_data['violation_code_extracted'] = train_data['violation_code_extracted'].str.replace(r'^(\d{2}).*', r'\1')
test_data['violation_code_extracted'] = test_data['violation_code_extracted'].str.replace(r'^(\d{2}).*', r'\1')
train_data['violation_code_extracted'].unique()
train_data.drop(['violation_code'], axis = 1, inplace = True)
test_data.drop(['violation_code'], axis = 1, inplace = True)

In [24]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(handle_unknown = "ignore")
encode_data = train_data[['agency_name','disposition', 'violation_code_extracted']]
encode_data_test = test_data[['agency_name','disposition', 'violation_code_extracted']]
encoder.fit(encode_data)
encode_data = encoder.transform(encode_data)
encode_data_test = encoder.transform(encode_data_test)
#print(encoder.categories_)
encode_train_df = pd.DataFrame(encode_data.toarray())
encode_test_df = pd.DataFrame(encode_data_test.toarray())
train_data.reset_index(inplace = True, drop =True)
test_data.reset_index(inplace = True, drop =True)
train_data = pd.concat([train_data, encode_train_df], axis = 1)
test_data = pd.concat([test_data, encode_test_df], axis = 1)
train_data.rename(columns = {0:'Buildings,Safety & Env Dept.', 1:'Public Works', 2:'Police',3:'Health Dept.', 4:'City Halls',
                   5:'Responsible (Fine Waived) by Deter', 6:'Responsible by Admission', 7:'Responsible by Default',
                             8:'Responsible by Determination', 9:'Violation code:19', 10:'Violation code:20', 11:'Violation code:22', 12:'Violation code:61', 13:'Violation code::9-1'}, inplace = True)
train_data.drop(['agency_name','disposition', 'violation_code_extracted'],axis = 1, inplace = True)

test_data.rename(columns = {0:'Buildings,Safety & Env Dept.', 1:'Public Works', 2:'Police',3:'Health Dept.', 4:'City Halls',
                   5:'Responsible (Fine Waived) by Deter', 6:'Responsible by Admission', 7:'Responsible by Default',
                             8:'Responsible by Determination', 9:'Violation code:19', 10:'Violation code:20', 11:'Violation code:22', 12:'Violation code:61', 13:'Violation code::9-1'}, inplace = True)
test_data.drop(['agency_name','disposition', 'violation_code_extracted'],axis = 1, inplace = True)

Two extra datasets have been provided - readonly/addresses.csv & readonly/latlons.csv - which can be used to replace address-related features with coordinates of the address

In [25]:
address_data = pd.read_csv('addresses.csv', engine='python')
latlon_data = pd.read_csv('latlons.csv', engine='python')
train_data.head()

,ticket_id,fine_amount,admin_fee,state_fee,late_fee,discount_amount,clean_up_cost,judgment_amount,compliance,"Buildings,Safety & Env Dept.",...,City Halls,Responsible (Fine Waived) by Deter,Responsible by Admission,Responsible by Default,Responsible by Determination,Violation code:19,Violation code:20,Violation code:22,Violation code:61,Violation code::9-1
0,22056,250.0,20.0,10.0,25.0,0.0,0.0,305.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,27586,750.0,20.0,10.0,75.0,0.0,0.0,855.0,1.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,22046,250.0,20.0,10.0,25.0,0.0,0.0,305.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,18738,750.0,20.0,10.0,75.0,0.0,0.0,855.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,18735,100.0,20.0,10.0,10.0,0.0,0.0,140.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [26]:
test_data.sample(10)

,ticket_id,fine_amount,admin_fee,state_fee,late_fee,discount_amount,clean_up_cost,judgment_amount,"Buildings,Safety & Env Dept.",Public Works,...,City Halls,Responsible (Fine Waived) by Deter,Responsible by Admission,Responsible by Default,Responsible by Determination,Violation code:19,Violation code:20,Violation code:22,Violation code:61,Violation code::9-1
39659,345777,100.0,20.0,10.0,0.0,0.0,0.0,130.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9516,301549,1000.0,20.0,10.0,100.0,0.0,0.0,1130.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
12111,305386,200.0,20.0,10.0,20.0,0.0,0.0,250.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
23241,321901,50.0,20.0,10.0,5.0,0.0,0.0,85.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
45947,354124,100.0,20.0,10.0,10.0,0.0,0.0,140.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
12017,306025,50.0,20.0,10.0,5.0,0.0,0.0,85.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
60729,375110,250.0,20.0,10.0,0.0,0.0,0.0,280.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
40561,346028,50.0,20.0,10.0,5.0,0.0,0.0,85.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
7486,298337,200.0,20.0,10.0,20.0,0.0,0.0,250.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
21808,321608,250.0,20.0,10.0,25.0,0.0,0.0,305.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

K-NN Regression

In [27]:
address_data.head()

   ticket_id                      address
0      22056       2900 tyler, Detroit MI
1      27586     4311 central, Detroit MI
2      22062  1449 longfellow, Detroit MI
3      22084  1441 longfellow, Detroit MI
4      22093   2449 churchill, Detroit MI

In [28]:
latlon_data.head()

                                  address        lat        lon
0  4300 rosa parks blvd, Detroit MI 48208  42.346169 -83.079962
1                14512 sussex, Detroit MI  42.394657 -83.194265
2                3456 garland, Detroit MI  42.373779 -82.986228
3                5787 wayburn, Detroit MI  42.403342 -82.957805
4              5766 haverhill, Detroit MI  42.407255 -82.946295

In [29]:
train_data.isna().sum()

ticket_id                             0
fine_amount                           0
admin_fee                             0
state_fee                             0
late_fee                              0
discount_amount                       0
clean_up_cost                         0
judgment_amount                       0
compliance                            0
Buildings,Safety & Env Dept.          0
Public Works                          0
Police                                0
Health Dept.                          0
City Halls                            0
Responsible (Fine Waived) by Deter    0
Responsible by Admission              0
Responsible by Default                0
Responsible by Determination          0
Violation code:19                     0
Violation code:20                     0
Violation code:22                     0
Violation code:61                     0
Violation code::9-1                   0
dtype: int64

In [30]:
test_data.isna().sum()

ticket_id                             0
fine_amount                           0
admin_fee                             0
state_fee                             0
late_fee                              0
discount_amount                       0
clean_up_cost                         0
judgment_amount                       0
Buildings,Safety & Env Dept.          0
Public Works                          0
Police                                0
Health Dept.                          0
City Halls                            0
Responsible (Fine Waived) by Deter    0
Responsible by Admission              0
Responsible by Default                0
Responsible by Determination          0
Violation code:19                     0
Violation code:20                     0
Violation code:22                     0
Violation code:61                     0
Violation code::9-1                   0
dtype: int64

In [35]:
from sklearn.model_selection import train_test_split
y= train_data['compliance']
X = train_data.drop(['compliance', 'ticket_id', 'Violation code:19', 'Violation code:20', 'Violation code:22',
       'Violation code:61', 'Violation code::9-1'], axis = 1)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0)

In [36]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GridSearchCV
rfclf = RandomForestClassifier()
grid_values = {'max_features' : ['auto', 'sqrt', 'log2'], 'n_estimators' : [10, 50, 100]}
grid_clf_acc = GridSearchCV(rfclf, param_grid = grid_values, scoring = 'roc_auc')
grid_clf_acc.fit(X_train, y_train)
#y_decision_fn_scores_acc = grid_clf_acc.decision_function(X_test)
y_predict = grid_clf_acc.predict(X_test)
#print(roc_auc_score(y_test, y_predict))
print(roc_auc_score(y_test, y_decision_fn_scores_acc))

c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\model_selection\_split.py:1943: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)

AttributeError: 'RandomForestClassifier' object has no attribute 'decision_function'

In [37]:
y_predict = grid_clf_acc.predict(X_test)
print(roc_auc_score(y_test, y_predict))
print('Grid best parameter (max. accuracy): ', grid_clf_acc.best_params_)
X_validation = test_data
X_test.columns

0.6204208250040504
Grid best parameter (max. accuracy):  {'max_features': 'log2', 'n_estimators': 100}

Index(['fine_amount', 'admin_fee', 'state_fee', 'late_fee', 'discount_amount',
       'clean_up_cost', 'judgment_amount', 'Buildings,Safety & Env Dept.',
       'Public Works', 'Police', 'Health Dept.', 'City Halls',
       'Responsible (Fine Waived) by Deter', 'Responsible by Admission',
       'Responsible by Default', 'Responsible by Determination'],
      dtype='object')

In [ ]:
def blight_model():
    
    # Your code here
    
    return # Your answer here